# Generated by Django 2.2.7 on 2019-11-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20191124_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author',
        ),
        migrations.AddField(
            model_name='commit',
            name='author_name',
            field=models.CharField(default='davidpierre21', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
