# Generated by Django 2.2.7 on 2019-11-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20191126_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='owner_username',
            field=models.CharField(default='davidpierre21', max_length=255),
            preserve_default=False,
        ),
    ]
