# Generated by Django 2.2.7 on 2019-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20191126_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='repository',
            name='url',
            field=models.URLField(default='todo-api'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner_avatar_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
