# Generated by Django 2.2.7 on 2019-11-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20191126_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner_avatar_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
