# Generated by Django 2.2.7 on 2019-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20191127_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner_avatar_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
