# Generated by Django 2.2.7 on 2019-11-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20191129_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='owner_avatar_url',
        ),
    ]
