# Generated by Django 2.2.7 on 2019-12-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_repository_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together={('name', 'owner_login')},
        ),
    ]
