# Generated by Django 2.2.7 on 2019-12-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20191202_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set(),
        ),
    ]
